name:                antiope-s3
version:             6.4.0
github:              "arbor/antiope"
license:             MIT
category:            Services
author:              Arbor Networks
maintainer:          mayhem@arbor.net
copyright:           Arbor Networks

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Data

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/arbor/antiope#readme>

default-extensions:
- BangPatterns
- GeneralizedNewtypeDeriving
- OverloadedStrings
- TupleSections

dependencies:
- base >= 4.7 && < 5
- aeson
- amazonka        >= 1.6.1
- amazonka-core   >= 1.6.1
- amazonka-s3     >= 1.6.1
- antiope-core
- attoparsec
- bytestring
- conduit
- conduit-extra
- exceptions
- generic-lens
- http-types
- lens
- monad-logger
- mtl
- network-uri
- resourcet
- text
- time
- unliftio-core

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints
- -msse4.2

library:
  source-dirs: src

tests:
  antiope-s3-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - antiope-core
    - antiope-s3
    - hedgehog            >= 0.5        && < 0.7
    - hspec               >= 2.4        && < 2.6
    - hw-hspec-hedgehog   >= 0.1        && < 0.2
